### **Basic Level:**

### 1. Write a Python program to print the numbers from 1 to 10 using a `for` loop.

In [1]:
# Using a for loop to iterate over a range of numbers from 1 to 10
for i in range(1, 11):
    # Printing the current value of the loop variable 'i'
    print(i)

1
2
3
4
5
6
7
8
9
10


- `for i in range(1, 11):` This line initiates a `for` loop, where `i` is a loop variable that takes values from 1 to 10 (inclusive).
- `range(1, 11)` generates a sequence of numbers starting from 1 up to, but not including, 11.
- `print(i)` Inside the loop, this line prints the current value of the loop variable i on each iteration.
- As the loop iterates from 1 to 10, it prints the numbers one by one.

### 2. Create a program that calculates the sum of all numbers in a list using a `for` loop.

In [9]:
# Sample list of numbers
numbers = [3, 7, 1, 5, 9]

# Initialize a variable to store the sum
sum_result = 0

# Using a for loop to iterate over each element in the list
for num in numbers:
    # Add the current number to the sum
    sum_result += num

# Print the final sum
print("Sum:", sum_result)

Sum: 25


- `numbers = [3, 7, 1, 5, 9]` This line creates a sample list called numbers containing some numerical values.
- `sum_result = 0`Initializes a variable `sum_result` to store the sum of the numbers. It starts with an initial value of 0.
- `for num in numbers:`Initiates a for loop that iterates over each element `(num)` in the numbers list.
 `sum_result += num` Inside the loop, adds the current number `(num)` to the running sum.
- `print("Sum:", sum_result)`After the loop, prints the final sum calculated from the elements in the list.

### 3. Write a program to print the characters of a string in reverse order using a `for` loop.

In [13]:
# Sample string
input_string = "Rajan"

# Using a for loop to iterate over the string in reverse order
for char in reversed(input_string):
    # Printing each character
    print(char, end=" ")

# Optional: Print a newline for better formatting
print()

n a j a R 


- input_string = "Rajan"This line creates a sample string called input_string with the value "Rajan".
- for char in reversed(input_string):Initiates a for loop that iterates over each character (char) in the input_string, but in reverse order.
- reversed(input_string) is used to reverse the order of the characters.
- print(char, end="")Inside the loop, prints each character without adding a newline character (end="" is used to achieve this).
- This ensures that the characters are printed on the same line.
- print()

### 4. Develop a program that finds the factorial of a given number using a `for` loop.

In [17]:
# Function to calculate the factorial of a number
def factorial(n):
    # Initialize the result to 1
    result = 1

    # Using a for loop to multiply numbers from 1 to n
    for i in range(1, n + 1):
        result *= i

    return result

# Input: the number for which factorial needs to be calculated
number = int(input("Enter a number: "))

# Calculate and print the factorial
print("Factorial of", number, "is:", factorial(number))

Enter a number:  5


Factorial of 5 is: 120


- def factorial(n): This line defines a function named factorial that takes a parameter n.

- result = 1 Initializes a variable result to store the factorial. It starts with an initial value of 1.

- for i in range(1, n + 1): Initiates a for loop that iterates from 1 to n (inclusive).

- result *= iInside the loop, multiplies the current loop variable i with the running result to accumulate the factorial.

- return result Returns the final factorial value calculated.

- number = int(input("Enter a number: ")) Takes user input for the number for which the factorial needs to be calculated.

- print("Factorial of", number, "is:", factorial(number)) Calls the factorial function with the user-input number and prints the result.

### 5. Create a program to print the multiplication table of a given number using a `for` loop.

In [25]:
# Function to print the multiplication table of a given number
def multiplication_table(number):
    print(f"Multiplication Table for {number}:")

    # Using a for loop to iterate from 1 to 10
    for i in range(1, 11):
        multi = number * i
        print(f"{number} x {i} = {multi}")

# Input: the number for which the multiplication table needs to be printed
number = int(input("Enter a number: "))

# Call the function to print the multiplication table
multiplication_table(number)

Enter a number:  8


Multiplication Table for 8:
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80


- def multiplication_table(number): This line defines a function named multiplication_table that takes a parameter number.
- print(f"Multiplication Table for {number}:") Prints a header indicating the multiplication table for the given number.
- for i in range(1, 11): Initiates a for loop that iterates from 1 to 10 (inclusive), representing the multipliers in the multiplication table.
- multi = number * i Calculates the product of the given number and the current multiplier i.
- print(f"{number} x {i} = {multi}") Prints each multiplication expression and its result in a formatted way.
- number = int(input("Enter a number: ")) Takes user input for the number for which the multiplication table needs to be printed.
- multiplication_table(number) Calls the multiplication_table function with the user-input number to print the multiplication table.

### 6. Write a program that counts the number of even and odd numbers in a list using a `for` loop.

In [28]:
# Sample list of numbers
numbers = [2, 7, 14, 5, 8, 10, 3, 6]

# Initialize counters for even and odd numbers
even_count = 0
odd_count = 0

# Using a for loop to iterate over each element in the list
for num in numbers:
    # Check if the number is even or odd
    if num % 2 == 0:
        even_count += 1
    else:
        odd_count += 1

# Print the results
print("Number of even numbers:", even_count)
print("Number of odd numbers:", odd_count)

Number of even numbers: 5
Number of odd numbers: 3


- numbers = [2, 7, 14, 5, 8, 10, 3, 6] This line creates a sample list called numbers containing some numerical values.

- even_count = 0 and odd_count = 0 Initialize counters for even and odd numbers, both starting with a value of 0.

- for num in numbers: Initiates a for loop that iterates over each element (num) in the numbers list.

- if num % 2 == 0: Inside the loop, checks if the current number is even by using the modulo operator (%).

- even_count += 1 and odd_count += 1 Increments the respective counters based on whether the current number is even or odd.
- print("Number of even numbers:", even_count) and print("Number of odd numbers:", odd_count) Prints the final counts of even and odd numbers after the loop.

### 7. Develop a program that prints the squares of numbers from 1 to 5 using a `for` loop.

In [30]:
# Using a for loop to iterate over numbers from 1 to 5
for i in range(1, 6):
    # Calculate the square of the current number
    square = i ** 2

    # Print the square
    print(f"The square of {i} is: {square}")

The square of 1 is: 1
The square of 2 is: 4
The square of 3 is: 9
The square of 4 is: 16
The square of 5 is: 25


- for i in range(1, 6): This line initiates a for loop that iterates over numbers from 1 to 5 (range(1, 6)).
- square = i ** 2 Inside the loop, calculates the square of the current number i using the exponentiation operator (**).
- print(f"The square of {i} is: {square}") Prints the result in a formatted string, indicating the original number and its square.

### 8. Create a program to find the length of a string without using the `len()` function.

In [31]:
# Function to find the length of a string without using len()
def find_string_length(input_string):
    length = 0

    # Using a for loop to iterate through each character in the string
    for char in input_string:
        length += 1

    return length

# Input: the string for which length needs to be calculated
user_input = input("Enter a string: ")

# Call the function to find the length and print the result
print("Length of the string:", find_string_length(user_input))

Enter a string:  Rajan


Length of the string: 5


- def find_string_length(input_string): This line defines a function named find_string_length that takes a parameter input_string.
- length = 0 Initializes a variable length to store the length of the string. It starts with an initial value of 0.
- for char in input_string: Initiates a for loop that iterates through each character (char) in the input_string.
- length += 1 Inside the loop, increments the length variable for each character encountered.
- return length Returns the final length of the string calculated.
- user_input = input("Enter a string: ")Takes user input for the string for which the length needs to be calculated.
- print("Length of the string:", find_string_length(user_input)) Calls the find_string_length function with the user-input string and prints the result.

### 9. Write a program that calculates the average of a list of numbers using a `for` loop.

In [36]:
# list of numbers
numbers = [5, 12, 8, 16, 3, 7]

# Initialize variables for sum and count
sum_numbers = 0
count = 0

# Using a for loop to iterate over each element in the list
for num in numbers:
    # Add the current number to the sum
    sum_numbers += num
    # Increment the count
    count += 1

# Calculate the average
average = sum_numbers / count

# Print the result
print("Average of the numbers:", average)

Average of the numbers: 8.5


- numbers = [5, 12, 8, 16, 3, 7] This line creates a sample list called numbers containing some numerical values.

- sum_numbers = 0 and count = 0 Initialize variables for the sum of numbers and the count of numbers, both starting with values of 0.
- for num in numbers: Initiates a for loop that iterates over each element (num) in the numbers list.

- sum_numbers += num and count += 1 Inside the loop, adds the current number to the running sum and increments the count for each iteration.
- average = sum_numbers / count Calculates the average by dividing the sum of numbers by the count of numbers.
- print("Average of the numbers:", average) Prints the final average of the numbers.

### 10. Develop a program that prints the first `n` Fibonacci numbers using a `for` loop.

In [37]:
# Function to print the first n Fibonacci numbers
def print_fibonacci(n):
    fib_sequence = [0, 1]

    # Using a for loop to generate Fibonacci numbers
    for i in range(2, n):
        next_fibonacci = fib_sequence[-1] + fib_sequence[-2]
        fib_sequence.append(next_fibonacci)

    # Print the Fibonacci sequence
    print(f"First {n} Fibonacci numbers:")
    for num in fib_sequence:
        print(num, end=" ")

# Input: the value of n
n = int(input("Enter the value of n: "))

# Call the function to print the Fibonacci sequence
print_fibonacci(n)

Enter the value of n:  8


First 8 Fibonacci numbers:
0 1 1 2 3 5 8 13 

- def print_fibonacci(n):This line defines a function named print_fibonacci that takes a parameter n.

- fib_sequence = [0, 1] Initializes a list fib_sequence with the first two Fibonacci numbers.
- for i in range(2, n):Initiates a for loop starting from the third Fibonacci number up to the n-th Fibonacci number.
- next_fibonacci = fib_sequence[-1] + fib_sequence[-2]Calculates the next Fibonacci number by adding the last two numbers in the sequence.
- fib_sequence.append(next_fibonacci)Appends the newly calculated Fibonacci number to the list.
- print(f"First {n} Fibonacci numbers:")Prints a header indicating the number of Fibonacci numbers to be displayed.
- for num in fib_sequence:Uses another for loop to iterate through the Fibonacci sequence and prints each number.
- print(num, end=" ")Prints each Fibonacci number separated by a space.
- n = int(input("Enter the value of n: "))Takes user input for the value of n.
- print_fibonacci(n)Calls the print_fibonacci function with the user-input value of n to print the Fibonacci sequence.

### **Intermediate Level:**

### 11. Write a program to check if a given list contains any duplicates using a `for` loop.

In [3]:
# Function to check for duplicates in a list
def has_duplicates(input_list):
    seen = set()

    # Using a for loop to iterate over each element in the list
    for element in input_list:
        # If the element is already in the set, it's a duplicate
        if element in seen:
            return True
        # Otherwise, add the element to the set
        seen.add(element)

    # No duplicates found
    return False

# Sample list with potential duplicates
my_list = [2, 4, 6, 8, 2, 10, 12]

# Call the function to check for duplicates and print the result
if has_duplicates(my_list):
    print("The list contains duplicates.")
else:
    print("The list does not contain duplicates.")

The list contains duplicates.


### 12. Create a program that prints the prime numbers in a given range using a `for` loop.

In [2]:
# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Function to print prime numbers in a given range
def print_primes_in_range(start, end):
    print(f"Prime numbers in the range {start} to {end}:")

    # Using a for loop to iterate over numbers in the given range
    for num in range(start, end + 1):
        if is_prime(num):
            print(num, end=" ")

# Input: the range for prime numbers
start_range = int(input("Enter the start of the range: "))
end_range = int(input("Enter the end of the range: "))

# Call the function to print prime numbers in the given range
print_primes_in_range(start_range, end_range)

Enter the start of the range:  10
Enter the end of the range:  30


Prime numbers in the range 10 to 30:
11 13 17 19 23 29 

- def is_prime(num):This line defines a function named is_prime that takes a number num and checks if it's prime.

- if num < 2: return FalseIf the number is less than 2, it's not prime.

- for i in range(2, int(num**0.5) + 1):Uses a for loop to iterate from 2 to the square root of the number plus 1.

- Checking up to the square root is sufficient for primality testing.

- if num % i == 0: return FalseIf the number is divisible by any integer in the range, it's not prime.

- return True

- If the loop completes without finding a divisor, the number is prime.

- def print_primes_in_range(start, end):Defines a function named print_primes_in_range that takes a start and end value for a range.

- for num in range(start, end + 1):Initiates a for loop to iterate over numbers in the given range.

- if is_prime(num): print(num, end=" ")Checks if each number is prime using the is_prime function and prints it if it is.

- start_range = int(input("Enter the start of the range: ")) and end_range = int(input("Enter the end of the range: ")) Takes user input for the start and end of the range.

- print_primes_in_range(start_range, end_range)Calls the print_primes_in_range function with the user-input range to print the prime numbers in that range.

### 13. Develop a program that counts the number of vowels in a string using a `for` loop.

In [3]:
# Function to count the number of vowels in a string
def count_vowels(input_string):
    vowels = "aeiouAEIOU"
    vowel_count = 0

    # Using a for loop to iterate through each character in the string
    for char in input_string:
        # Check if the character is a vowel
        if char in vowels:
            vowel_count += 1

    return vowel_count

# Input: the string for which vowels need to be counted
user_input = input("Enter a string: ")

# Call the function to count vowels and print the result
result = count_vowels(user_input)
print(f"Number of vowels in the string: {result}")

Enter a string:  Rajan


Number of vowels in the string: 2


- def count_vowels(input_string): This line defines a function named count_vowels that takes a parameter input_string.

- vowels = "aeiouAEIOU" Initializes a string vowels containing all lowercase and uppercase vowels.

- vowel_count = 0 Initializes a variable vowel_count to store the count of vowels, starting with an initial value of 0.

- for char in input_string: Initiates a for loop that iterates through each character (char) in the input_string.

- if char in vowels: Inside the loop, checks if the current character is a vowel by using the in operator.

- vowel_count += 1 If the character is a vowel, increments the vowel_count.

- return vowel_count Returns the final count of vowels.

- user_input = input("Enter a string: ") Takes user input for the string for which vowels need to be counted.

- result = count_vowels(user_input) Calls the count_vowels function with the user-input string and stores the result.

- print(f"Number of vowels in the string: {result}") Prints the final count of vowels in the given string.

### 14. Write a program to find the maximum element in a 2D list using a nested `for` loop.

In [7]:
# Function to find the maximum element in a 2D list
def find_max_element(matrix):
    max_element = matrix[0][0]
    
     # Using nested for loops to iterate through each element in the 2D list
    for row in matrix:
        for element in row:
            if(element>max_element):
                max_element = element
    return max_element

# sample 2D matrix
matrix = [
    [3,8,1],
    [5,2,7],
    [6,4,9]
]

# Call the function to find the maximum element and print the result
max_element = find_max_element(matrix)
print(f"The maximum element in the 2D list is: {max_element}")

The maximum element in the 2D list is: 9


- def find_max_element(matrix):This line defines a function named find_max_element that takes a 2D list matrix.

- max_element = matrix[0][0] Initializes a variable max_element with the first element of the 2D list.

- for row in matrix:Initiates the outer for loop to iterate through each row in the 2D list.

- for element in row:Initiates the inner for loop to iterate through each element in the current row.

- if element > max_element: Inside the nested loops, checks if the current element is greater than the current max_element.

- max_element = element If the current element is greater, updates max_element with the new maximum value.

- return max_element Returns the final maximum element found in the 2D list.

- matrix = [...] Creates a sample 2D list named matrix.

- max_element = find_max_element(matrix) Calls the function to find the maximum element in the 2D list and stores the result.

- print(f"The maximum element in the 2D list is: {max_element}") Prints the result.

### 15. Create a program that removes all occurrences of a specific element from a list using a `for` loop.

In [21]:
# Function to remove all occurrences of a specific element from a list
def remove_element(lst, target):
    # Using a for loop to iterate through each element in the list
    for element in lst:
        # Check if the current element is equal to the target
        if element == target:
            # Remove the element from the list
            lst.remove(element)

# Sample list
my_list = [2, 3, 4, 2, 6, 2, 8, 2]

# Input: the element to be removed
target_element = 2

# Call the function to remove the target element from the list
remove_element(my_list, target_element)

# Print the modified list
print("List after removing all occurrences of", target_element, ":", my_list)

List after removing all occurrences of 2 : [3, 4, 6, 8]


- def remove_element(lst, target): This line defines a function named remove_element that takes a list lst and a target element target.

- for element in lst: Initiates a for loop that iterates through each element in the list lst.

- if element == target: Inside the loop, checks if the current element is equal to the target element.

- lst.remove(element) If the element is equal to the target, removes that element from the list.

- my_list = [2, 3, 4, 2, 6, 2, 8, 2] Creates a sample list named my_list containing some elements.

- target_element = int(input("Enter the element to remove: ")) Takes user input for the element to be removed from the list.

- remove_element(my_list, target_element) Calls the remove_element function to remove all occurrences of the target element from my_list.

- print("List after removing all occurrences of", target_element, ":", my_list)Prints the modified list after removing all occurrences of the target element.

### 16. Develop a program that generates a multiplication table for numbers from 1 to 5 using a nested `for` loop.

In [22]:
# Using nested for loops to generate a multiplication table
for i in range(1, 6):  # Outer loop for multiplicand
    print(f"\nMultiplication table for {i}:")
    for j in range(1, 11):  # Inner loop for multiplier
        result = i * j
        print(f"{i} x {j} = {result}")


Multiplication table for 1:
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10

Multiplication table for 2:
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

Multiplication table for 3:
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

Multiplication table for 4:
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

Multiplication table for 5:
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


- Outer Loop (for i in range(1, 6):): This loop iterates over the multiplicands from 1 to 5.

- Inner Loop (for j in range(1, 11):):Nested inside the outer loop, this loop iterates over the multipliers from 1 to 10 for each multiplicand.

- result = i * j: Calculates the product of the current multiplicand i and multiplier j.

- print(f"{i} x {j} = {result}"): Prints the multiplication table entry in a formatted string.

### 17. Write a program that converts a list of Fahrenheit temperatures to Celsius using a `for` loop.

In [23]:
# Function to convert Fahrenheit to Celsius
def fahrenheit_to_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9

# Sample list of Fahrenheit temperatures
fahrenheit_temps = [32, 68, 104, 140, 176]

# Using a for loop to convert each temperature to Celsius
celsius_temps = []
for temp in fahrenheit_temps:
    celsius_temps.append(fahrenheit_to_celsius(temp))

# Print the original and converted temperatures
print("Fahrenheit Temperatures:", fahrenheit_temps)
print("Celsius Temperatures:", celsius_temps)

Fahrenheit Temperatures: [32, 68, 104, 140, 176]
Celsius Temperatures: [0.0, 20.0, 40.0, 60.0, 80.0]


- def fahrenheit_to_celsius(fahrenheit):This line defines a function named fahrenheit_to_celsius that takes a Fahrenheit temperature and returns its equivalent in Celsius.

- return (fahrenheit - 32) * 5/9 Converts Fahrenheit to Celsius using the conversion formula.

- fahrenheit_temps = [32, 68, 104, 140, 176] Creates a sample list named fahrenheit_temps containing Fahrenheit temperatures.

- Using a for loop to iterate through each Fahrenheit temperature in fahrenheit_temps and convert it to Celsius.

- celsius_temps = [] Initializes an empty list celsius_temps to store the converted temperatures.

- for temp in fahrenheit_temps: Initiates a for loop to iterate through each Fahrenheit temperature in the list.

- celsius_temps.append(fahrenheit_to_celsius(temp)) Appends the converted Celsius temperature to the celsius_temps list.

- print("Fahrenheit Temperatures:", fahrenheit_temps) Prints the original Fahrenheit temperatures.

- print("Celsius Temperatures:", celsius_temps) Prints the corresponding Celsius temperatures.

### 18. Create a program to print the common elements from two lists using a `for` loop.

In [1]:
# Function to find common elements between two lists
def find_common_elements(list1, list2):
    common_elements = []

    # Using a for loop to iterate through elements in the first list
    for element1 in list1:
        # Using another for loop to iterate through elements in the second list
        for element2 in list2:
            # Check if the elements are the same
            if element1 == element2:
                common_elements.append(element1)

    return common_elements

# Sample lists
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

# Call the function to find common elements and print the result
common_elements = find_common_elements(list1, list2)
print("Common elements:", common_elements)

Common elements: [3, 4, 5]


- def find_common_elements(list1, list2): This line defines a function named find_common_elements that takes two lists, list1 and list2.
- common_elements = []Initializes an empty list to store the common elements.
- Using a nested for loop structure:
- Outer Loop (for element1 in list1:):Iterates through each element in the first list (list1).
- Inner Loop (for element2 in list2:):Iterates through each element in the second list (list2).
- if element1 == element2: Checks if the current elements from both lists are the same.
- If they are, appends the element to the common_elements list.
- return common_elements Returns the list of common elements.
- list1 = [1, 2, 3, 4, 5] and list2 = [3, 4, 5, 6, 7] Creates two sample lists.
- common_elements = find_common_elements(list1, list2)Calls the function to find common elements between list1 and list2 and stores the result.
- print("Common elements:", common_elements) Prints the common elements found in both lists.

### 19. Develop a program that prints the pattern of right-angled triangles using a `for` loop. Use ‘*’ to draw the pattern

In [2]:
# Function to print right-angled triangles pattern
def print_right_triangle_pattern(rows):
    for i in range(1, rows + 1):
        for j in range(1, i + 1):
            print('*', end=' ')
        print()

# Input: Number of rows in the pattern
num_rows = int(input("Enter the number of rows for the right-angled triangles pattern: "))

# Call the function to print the pattern
print_right_triangle_pattern(num_rows)

Enter the number of rows for the right-angled triangles pattern:  5


* 
* * 
* * * 
* * * * 
* * * * * 


- def print_right_triangle_pattern(rows):This line defines a function named print_right_triangle_pattern that takes the number of rows (rows) as a parameter.
- Using nested for loops to print the pattern:
- Outer Loop (for i in range(1, rows + 1):): Iterates through each row.
- Inner Loop (for j in range(1, i + 1):):Iterates through each column in the current row.
- print('*', end=' ') Prints '*' without moving to the next line.
- print() Moves to the next line after printing the '*' characters for the current row.
- num_rows = int(input("Enter the number of rows for the right-angled triangles pattern: ")) Takes user input for the number of rows in the pattern.
- print_right_triangle_pattern(num_rows) Calls the function to print the right-angled triangles pattern with the specified number of rows.

### 20. Write a program to find the greatest common divisor (GCD) of two numbers using a `for` loop

In [5]:
# Function to find the greatest common divisor (GCD) of two numbers
def find_gcd(num1, num2):
    # Choose the smaller of the two numbers as the initial guess for GCD
    gcd = min(num1, num2)

    # Using a for loop to iterate from the initial guess towards 1
    for i in range(gcd, 0, -1):
        if num1 % i == 0 and num2 % i == 0:
            # If both numbers are divisible by i, i is the GCD
            gcd = i
            break

    return gcd

# Input: two numbers for which GCD needs to be found
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# Call the function to find the GCD and print the result
gcd_result = find_gcd(num1, num2)
print(f"The Greatest Common Divisor (GCD) of {num1} and {num2} is: {gcd_result}")

Enter the first number:  48
Enter the second number:  18


The Greatest Common Divisor (GCD) of 48 and 18 is: 6


- def find_gcd(num1, num2): This line defines a function named find_gcd that takes two numbers, num1 and num2.
- gcd = min(num1, num2) Initializes gcd with the smaller of the two numbers.
- Using a for loop to iterate from the initial guess (gcd) towards 1. 
- for i in range(gcd, 0, -1): The loop iterates from the initial guess towards 1 in reverse order.
- if num1 % i == 0 and num2 % i == 0:Checks if both numbers are divisible by the current value of i.
- gcd = i If the condition is true, updates gcd with the current value of i (found GCD).
- break Breaks out of the loop since the GCD has been found.
- return gcd Returns the GCD.
- Takes user input for the two numbers. 
- gcd_result = find_gcd(num1, num2) Calls the function to find the GCD of the two numbers.
- print(f"The Greatest Common Divisor (GCD) of {num1} and {num2} is: {gcd_result}") Prints the result.

### **Advanced Level:**

### 21. Create a program that calculates the sum of the digits of numbers in a list using a list comprehension.

In [1]:
# Function to calculate the sum of digits of a number
def sum_of_digits(number):
    return sum(int(digit) for digit in str(abs(number)))

# Sample list of numbers
numbers_list = [123, 456, 789]

# Using a list comprehension to calculate the sum of digits for each number in the list
sums_list = [sum_of_digits(num) for num in numbers_list]

# Print the original list and the corresponding sums of digits
print("Original List of Numbers:", numbers_list)
print("Sums of Digits for Each Number:", sums_list)

Original List of Numbers: [123, 456, 789]
Sums of Digits for Each Number: [6, 15, 24]


- def sum_of_digits(number):This line defines a function named sum_of_digits that takes a number and calculates the sum of its digits.
- return sum(int(digit) for digit in str(abs(number))) Converts the absolute value of the number to a string, iterates through each digit, converts it back to an integer, and then calculates the sum of these digits.

- numbers_list = [123, 456, 789]Creates a sample list named numbers_list containing numbers.
- Using a list comprehension to calculate the sum of digits for each number in the list.
- sums_list = [sum_of_digits(num) for num in numbers_list] Calls the sum_of_digits function for each number in the list using a list comprehension and stores the results in a new list.
- print("Original List of Numbers:", numbers_list) Prints the original list of numbers.
- print("Sums of Digits for Each Number:", sums_list) Prints the corresponding sums of digits for each number.

### 22. Write a program to find the prime factors of a given number using a `for` loop and list comprehension.

In [3]:
# Function to find prime factors of a number
def prime_factors(number):
    return [i for i in range(2, number + 1) if number % i == 0 and all(i % j != 0 for j in range(2, int(i**0.5) + 1))]

# Input: Number for which prime factors need to be found
num = int(input("Enter a number to find its prime factors: "))

# Call the function to find prime factors and print the result
factors = prime_factors(num)
print(f"Prime factors of {num} are: {factors}")

Enter a number to find its prime factors:  18


Prime factors of 18 are: [2, 3]


- def prime_factors(number): This line defines a function named prime_factors that takes a number and returns a list of its prime factors.
- [i for i in range(2, number + 1) if number % i == 0 and all(i % j != 0 for j in range(2, int(i**0.5) + 1))]Using list comprehension to generate a list of prime factors:
- Iterates through numbers i from 2 to the given number (number).
- Checks if number is divisible by i and i is a prime number (no divisors other than 1 and itself).
- num = int(input("Enter a number to find its prime factors: "))Takes user input for the number for which prime factors need to be found.
- factors = prime_factors(num) Calls the function to find the prime factors of the entered number.
- print(f"Prime factors of {num} are: {factors}") Prints the result.

### 23. Develop a program that extracts unique elements from a list and stores them in a new list using a list comprehension

In [5]:
# Sample list with duplicate elements
original_list = [1, 2, 2, 3, 4, 4, 5, 6, 6, 7]

# Using list comprehension to extract unique elements
unique_list = list(set(original_list))

# Print the original and unique lists
print("Original List:", original_list)
print("Unique List:", unique_list)

Original List: [1, 2, 2, 3, 4, 4, 5, 6, 6, 7]
Unique List: [1, 2, 3, 4, 5, 6, 7]


- original_list = [1, 2, 2, 3, 4, 4, 5, 6, 6, 7] Creates a sample list with duplicate elements.
- unique_list = list(set(original_list)) Uses a set to automatically eliminate duplicate elements.
- Converts the set back to a list to maintain the original order.
- This line extracts unique elements from the original list.
- print("Original List:", original_list)  Prints the original list with duplicate elements.
- print("Unique List:", unique_list) Prints the list containing only unique elements.

### 24. Create a program that generates a list of all palindromic numbers up to a specified limit using a list comprehension.

In [6]:
# Function to check if a number is a palindrome
def is_palindrome(number):
    return str(number) == str(number)[::-1]

# Function to generate a list of palindromic numbers up to a limit
def palindromic_numbers(limit):
    return [num for num in range(limit + 1) if is_palindrome(num)]

# Input: Upper limit for palindromic numbers
upper_limit = int(input("Enter the upper limit for palindromic numbers: "))

# Call the function to generate the list and print the result
palindrome_list = palindromic_numbers(upper_limit)
print(f"Palindromic numbers up to {upper_limit}: {palindrome_list}")

Enter the upper limit for palindromic numbers:  50


Palindromic numbers up to 50: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33, 44]


- def is_palindrome(number): This line defines a function named is_palindrome that checks if a given number is a palindrome.
- return str(number) == str(number)[::-1] Converts the number to a string and checks if it is equal to its reverse.
- def palindromic_numbers(limit): This line defines a function named palindromic_numbers that generates a list of palindromic numbers up to a specified limit.
- [num for num in range(limit + 1) if is_palindrome(num)] Uses a list comprehension to generate a list of palindromic numbers:
- Iterates through numbers from 0 to the specified limit.
- Checks if each number is a palindrome using the is_palindrome function.
- upper_limit = int(input("Enter the upper limit for palindromic numbers: ")) Takes user input for the upper limit of palindromic numbers.
- palindrome_list = palindromic_numbers(upper_limit) Calls the function to generate the list of palindromic numbers up to the specified limit.
- print(f"Palindromic numbers up to {upper_limit}: {palindrome_list}") Prints the result.

### 25. Write a program to flatten a nested list using list comprehension.

In [7]:
# Function to flatten a nested list
def flatten_list(nested_list):
    return [item for sublist in nested_list for item in (flatten_list(sublist) if isinstance(sublist, list) else [sublist])]

# Sample nested list
nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]

# Using list comprehension to flatten the nested list
flattened_list = flatten_list(nested_list)

# Print the original nested list and the flattened list
print("Original Nested List:", nested_list)
print("Flattened List:", flattened_list)

Original Nested List: [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
Flattened List: [1, 2, 3, 4, 5, 6, 7, 8, 9]


- def flatten_list(nested_list): This line defines a recursive function named flatten_list that flattens a nested list.
[item for sublist in nested_list for item in (flatten_list(sublist) if isinstance(sublist, list) else [sublist])]

- Uses list comprehension to flatten the nested list:
- Iterates through each sublist in the nested list.
- Checks if the sublist is itself a list.
- If yes, recursively calls flatten_list on the sublist.
- If not, creates a list with the single item.
- Flattens the sublist and appends its items to the result list.
- nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]] Creates a sample nested list.
- flattened_list = flatten_list(nested_list) Calls the function to flatten the nested list.
- print("Original Nested List:", nested_list) Prints the original nested list.
- print("Flattened List:", flattened_list) Prints the flattened list.

### 26. Develop a program that computes the sum of even and odd numbers in a list separately using list comprehension.

In [8]:
# Sample list of numbers
numbers_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Using list comprehension to compute the sum of even and odd numbers separately
sum_even = sum([num for num in numbers_list if num % 2 == 0])
sum_odd = sum([num for num in numbers_list if num % 2 != 0])

# Print the original list and the sums of even and odd numbers
print("Original List:", numbers_list)
print("Sum of Even Numbers:", sum_even)
print("Sum of Odd Numbers:", sum_odd)

Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Sum of Even Numbers: 20
Sum of Odd Numbers: 25


- numbers_list = [1, 2, 3, 4, 5, 6, 7, 8, 9] Creates a sample list of numbers.
- sum_even = sum([num for num in numbers_list if num % 2 == 0]) Uses list comprehension to create a list of even numbers and calculates the sum.
- sum_odd = sum([num for num in numbers_list if num % 2 != 0]) Uses list comprehension to create a list of odd numbers and calculates the sum.
- print("Original List:", numbers_list) Prints the original list of numbers.
- print("Sum of Even Numbers:", sum_even) Prints the sum of even numbers.
- print("Sum of Odd Numbers:", sum_odd) Prints the sum of odd numbers.

 ### 27.Create a program that generates a list of squares of odd numbers between 1 and 10 using list comprehension.


In [9]:
# Using list comprehension to generate a list of squares of odd numbers between 1 and 10
squares_of_odd_numbers = [num**2 for num in range(1, 11) if num % 2 != 0]

# Print the result
print("Squares of Odd Numbers between 1 and 10:", squares_of_odd_numbers)

Squares of Odd Numbers between 1 and 10: [1, 9, 25, 49, 81]


- [num**2 for num in range(1, 11) if num % 2 != 0] Uses list comprehension to generate a list of squares of odd numbers between 1 and 10.
- for num in range(1, 11) iterates through numbers from 1 to 10.
- if num % 2 != 0 filters out even numbers.
- num**2 calculates the square of each odd number.
- print("Squares of Odd Numbers between 1 and 10:", squares_of_odd_numbers) Prints the result.

### 28. Write a program that combines two lists into a dictionary using list comprehension.

In [10]:
# Sample lists
keys = ['name', 'age', 'city']
values = ['Rajan', 20, 'Bhopal']

# Using list comprehension to combine lists into a dictionary
combined_dict = {keys[i]: values[i] for i in range(min(len(keys), len(values)))}

# Print the result
print("Combined Dictionary:", combined_dict)

Combined Dictionary: {'name': 'Rajan', 'age': 20, 'city': 'Bhopal'}


- {keys[i]: values[i] for i in range(min(len(keys), len(values)))} Uses list comprehension to combine the two lists into a dictionary:
- for i in range(min(len(keys), len(values))) iterates through the indices up to the minimum length of the two lists.
- keys[i]: values[i] creates key-value pairs in the dictionary.
- print("Combined Dictionary:", combined_dict) Prints the result.

### 29. Develop a program that extracts the vowels from a string and stores them in a list using list comprehension.

In [12]:
# Function to check if a character is a vowel
def is_vowel(char):
    return char.lower() in ['a', 'e', 'i', 'o', 'u']

# Input: String
input_string = input("Enter a string: ")

# Using list comprehension to extract vowels from the string
vowels_list = [char for char in input_string if is_vowel(char)]

# Print the result
print("Original String:", input_string)
print("Vowels in the String:", vowels_list)

Enter a string:  Rajan


Original String: Rajan
Vowels in the String: ['a', 'a']


- def is_vowel(char): This line defines a function named is_vowel that checks if a character is a vowel.
- return char.lower() in ['a', 'e', 'i', 'o', 'u'] Converts the character to lowercase and checks if it is in the list of vowels.
- input_string = input("Enter a string: ") Takes user input for the string.
- [char for char in input_string if is_vowel(char)] Uses list comprehension to extract vowels from the string:
- for char in input_string iterates through each character in the input string.
- if is_vowel(char) checks if the character is a vowel using the is_vowel function.
- print("Original String:", input_string) Prints the original input string.
- print("Vowels in the String:", vowels_list) Prints the list containing the extracted vowels.

### 30. Create a program that removes all non-numeric characters from a list of strings using list comprehension.

In [15]:
# Sample list of strings
string_list = ['Raj123', '45kum', '6y7d8']

# Using list comprehension to remove non-numeric characters
numeric_strings = [''.join(char for char in string if char.isnumeric()) for string in string_list]

# Print the result
print("Original List of Strings:", string_list)
print("Numeric Strings:", numeric_strings)

Original List of Strings: ['Raj123', '45kum', '6y7d8']
Numeric Strings: ['123', '45', '678']


- [''.join(char for char in string if char.isnumeric()) for string in string_list] Uses list comprehension to create a new list of strings without non-numeric characters:
- for string in string_list iterates through each string in the original list.
- for char in string iterates through each character in the current string.
- if char.isnumeric() checks if the character is numeric.
- ''.join(...) joins the numeric characters back together into a string.
- print("Original List of Strings:", string_list) Prints the original list of strings.
- print("Numeric Strings:", numeric_strings) Prints the list containing strings without non-numeric characters.

### **Challenge Level:**

### 31. Write a program to generate a list of prime numbers using the Sieve of Eratosthenes algorithm and list comprehension.

In [16]:
def sieve_of_eratosthenes(limit):
    # Create a boolean list "is_prime" and initialize all elements to True
    is_prime = [True] * (limit + 1)
    
    # 0 and 1 are not prime
    is_prime[0] = is_prime[1] = False
    
    # Iterate through numbers from 2 to the square root of the limit
    for num in range(2, int(limit**0.5) + 1):
        if is_prime[num]:
            # Mark multiples of the current prime number as non-prime
            is_prime[num**2 : limit + 1 : num] = [False] * len(is_prime[num**2 : limit + 1 : num])

    # Use list comprehension to create a list of prime numbers
    primes = [num for num in range(2, limit + 1) if is_prime[num]]

    return primes

# Input: Upper limit for prime numbers
upper_limit = int(input("Enter the upper limit for prime numbers: "))

# Call the function to generate the list of prime numbers
prime_numbers = sieve_of_eratosthenes(upper_limit)

# Print the result
print(f"Prime numbers up to {upper_limit}: {prime_numbers}")

Enter the upper limit for prime numbers:  30


Prime numbers up to 30: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


- def sieve_of_eratosthenes(limit):This line defines a function named sieve_of_eratosthenes that implements the Sieve of Eratosthenes algorithm to find prime numbers up to a given limit.
- is_prime = [True] * (limit + 1) Initializes a boolean list is_prime with True values for each number up to the limit.
- for num in range(2, int(limit**0.5) + 1): Iterates through numbers from 2 to the square root of the limit.
- if is_prime[num]: Checks if the current number is marked as prime.
- is_prime[num**2 : limit + 1 : num] = [False] * len(is_prime[num**2 : limit + 1 : num]) Marks multiples of the current prime number as non-prime.
- primes = [num for num in range(2, limit + 1) if is_prime[num]] Uses list comprehension to create a list of prime numbers.
- Takes user input for the upper limit. prime_numbers = sieve_of_eratosthenes(upper_limit) Calls the function to generate the list of prime numbers.
- print(f"Prime numbers up to {upper_limit}: {prime_numbers}") Prints the result.

### 32. Create a program that generates a list of all Pythagorean triplets up to a specified limit using list comprehension.

In [17]:
# Function to check if a set of three numbers is a Pythagorean triplet
def is_pythagorean_triplet(a, b, c):
    return a**2 + b**2 == c**2

# Input: Upper limit for Pythagorean triplets
upper_limit = int(input("Enter the upper limit for Pythagorean triplets: "))

# Using list comprehension to generate a list of Pythagorean triplets
pythagorean_triplets = [(a, b, c) for a in range(1, upper_limit + 1) for b in range(a, upper_limit + 1) for c in range(b, upper_limit + 1) if is_pythagorean_triplet(a, b, c)]

# Print the result
print(f"Pythagorean triplets up to {upper_limit}: {pythagorean_triplets}")

Enter the upper limit for Pythagorean triplets:  10


Pythagorean triplets up to 10: [(3, 4, 5), (6, 8, 10)]


- def is_pythagorean_triplet(a, b, c): This line defines a function named is_pythagorean_triplet that checks if a set of three numbers is a Pythagorean triplet.
- return a**2 + b**2 == c**2 Checks if the sum of the squares of the first two numbers is equal to the square of the third number.
- upper_limit = int(input("Enter the upper limit for Pythagorean triplets: ")) Takes user input for the upper limit.
[(a, b, c) for a in range(1, upper_limit + 1) for b in range(a, upper_limit + 1) for c in range(b, upper_limit + 1) if is_pythagorean_triplet(a, b, c)]

- Uses list comprehension to generate a list of Pythagorean triplets:
- for a in range(1, upper_limit + 1) iterates through the possible values of a.
- for b in range(a, upper_limit + 1) iterates through the possible values of b (greater than or equal to a).
- for c in range(b, upper_limit + 1) iterates through the possible values of c (greater than or equal to b).
- if is_pythagorean_triplet(a, b, c) checks if the current set of numbers is a Pythagorean triplet.
- print(f"Pythagorean triplets up to {upper_limit}: {pythagorean_triplets}") Prints the result.

### 33. Develop a program that generates a list of all possible combinations of two lists using list comprehension.

In [18]:
# Sample lists
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']

# Using list comprehension to generate all possible combinations
combinations = [(x, y) for x in list1 for y in list2]

# Print the result
print("List 1:", list1)
print("List 2:", list2)
print("All Possible Combinations:", combinations)

List 1: [1, 2, 3]
List 2: ['a', 'b', 'c']
All Possible Combinations: [(1, 'a'), (1, 'b'), (1, 'c'), (2, 'a'), (2, 'b'), (2, 'c'), (3, 'a'), (3, 'b'), (3, 'c')]


- [(x, y) for x in list1 for y in list2] Uses list comprehension to create a list of all possible combinations of elements from list1 and list2:
- for x in list1 iterates through each element in list1.
- for y in list2 iterates through each element in list2.
- (x, y) creates a tuple representing a combination of an element from list1 and an element from list2.
- print("List 1:", list1) Prints the original content of list1.
- print("List 2:", list2) Prints the original content of list2.
- print("All Possible Combinations:", combinations) Prints the list containing all possible combinations.

### 34. Write a program that calculates the mean, median, and mode of a list of numbers using list comprehension.

In [1]:
from statistics import mean, median, mode

# Sample list of numbers
numbers_list = [3, 5, 2, 7, 5, 8, 2, 9, 4, 3]

# Calculate mean, median, and mode using list comprehension
calculated_mean = mean(numbers_list)
calculated_median = median(numbers_list)
calculated_mode = mode(numbers_list)

# Print the result
print("List of Numbers:", numbers_list)
print("Mean:", calculated_mean)
print("Median:", calculated_median)
print("Mode:", calculated_mode)

List of Numbers: [3, 5, 2, 7, 5, 8, 2, 9, 4, 3]
Mean: 4.8
Median: 4.5
Mode: 3


- from statistics import mean, median, mode Imports the mean, median, and mode functions from the statistics module.
- calculated_mean = mean(numbers_list) Calculates the mean of the list using the mean function.
- calculated_median = median(numbers_list) Calculates the median of the list using the median function.
- calculated_mode = mode(numbers_list) Calculates the mode of the list using the mode function.
- print("List of Numbers:", numbers_list) Prints the original list of numbers.
- print("Mean:", calculated_mean) Prints the calculated mean.
- print("Median:", calculated_median) Prints the calculated median.
- print("Mode:", calculated_mode) Prints the calculated mode.

### 35. Create a program that generates Pascal's triangle up to a specified number of rows using list comprehension.

In [2]:
# Function to generate Pascal's triangle up to a specified number of rows
def generate_pascals_triangle(rows):
    triangle = [[1] * (row + 1) for row in range(rows)]
    
    for row in range(2, rows):
        for col in range(1, row):
            triangle[row][col] = triangle[row - 1][col - 1] + triangle[row - 1][col]

    return triangle

# Input: Number of rows for Pascal's triangle
num_rows = int(input("Enter the number of rows for Pascal's triangle: "))

# Call the function to generate Pascal's triangle
pascals_triangle = generate_pascals_triangle(num_rows)

# Print the result
print(f"Pascal's Triangle with {num_rows} rows:")
for row in pascals_triangle:
    print(row)

Enter the number of rows for Pascal's triangle:  5


Pascal's Triangle with 5 rows:
[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]


- def generate_pascals_triangle(rows): This line defines a function named generate_pascals_triangle that generates Pascal's triangle up to a specified number of rows.
- triangle = [[1] * (row + 1) for row in range(rows)] Initializes the triangle with all elements set to 1 for each row.
- for row in range(2, rows): Iterates through rows starting from the third row (index 2).
- for col in range(1, row): Iterates through columns, excluding the first and last columns.
- triangle[row][col] = triangle[row - 1][col - 1] + triangle[row - 1][col] Calculates each element as the sum of the two elements directly above it.
- pascals_triangle = generate_pascals_triangle(num_rows) Calls the function to generate Pascal's triangle.
- for row in pascals_triangle: Iterates through each row of Pascal's triangle.
- print(row) Prints each row.

### 36. Develop a program that calculates the sum of the digits of a factorial of numbers from 1 to 5 using list comprehension.

In [3]:
# Function to calculate the factorial of a number
def factorial(n):
    return 1 if n == 0 or n == 1 else n * factorial(n - 1)

# Using list comprehension to calculate the sum of digits for factorials from 1 to 5
sums_of_digits = [sum(int(digit) for digit in str(factorial(num))) for num in range(1, 6)]

# Print the result
print("Factorials from 1 to 5:", [factorial(num) for num in range(1, 6)])
print("Sum of Digits for Factorials:", sums_of_digits)

Factorials from 1 to 5: [1, 2, 6, 24, 120]
Sum of Digits for Factorials: [1, 2, 6, 6, 3]


- def factorial(n): This line defines a function named factorial that calculates the factorial of a number.
- return 1 if n == 0 or n == 1 else n * factorial(n - 1) Implements the factorial calculation using recursion.
- sums_of_digits = [sum(int(digit) for digit in str(factorial(num))) for num in range(1, 6)] Uses list comprehension to calculate the sum of digits for factorials from 1 to 5:
- for num in range(1, 6) iterates through numbers from 1 to 5.
- str(factorial(num)) converts the factorial result to a string.
- int(digit) converts each digit in the string back to an integer.
- sum(...) calculates the sum of digits for each factorial.
- print("Factorials from 1 to 5:", [factorial(num) for num in range(1, 6)]) Prints the factorials for numbers from 1 to 5.
- print("Sum of Digits for Factorials:", sums_of_digits) Prints the list containing the sum of digits for each factorial.

### 37. Write a program that finds the longest word in a sentence using list comprehension.

In [5]:
# Input: Sentence
sentence = input("Enter a sentence: ")

# Using list comprehension to find the longest word in the sentence
longest_word = max([word.strip(".,?!") for word in sentence.split()], key=len)

# Print the result
print("Longest Word in the Sentence:", longest_word)

Enter a sentence:  I'm Rajan Kumar.


Longest Word in the Sentence: Rajan


- sentence = input("Enter a sentence: ") Takes user input for the sentence.
- [word.strip(".,?!") for word in sentence.split()] Uses list comprehension to create a list of words by splitting the sentence.
- for word in sentence.split() iterates through each word in the sentence word.strip(".,?!") removes punctuation from each word.
- max(..., key=len) Finds the element with the maximum length in the list of words.
- print("Longest Word in the Sentence:", longest_word) Prints the longest word found.

### 38. Create a program that filters a list of strings to include only those with more than three vowels using list comprehension.

In [6]:
# Function to count vowels in a string
def count_vowels(string):
    return sum(1 for char in string.lower() if char in 'aeiou')

# Sample list of strings
string_list = ["hello", "world", "python", "programming", "ai"]

# Using list comprehension to filter strings with more than three vowels
filtered_strings = [string for string in string_list if count_vowels(string) > 3]

# Print the result
print("Original List of Strings:", string_list)
print("Filtered Strings with More than Three Vowels:", filtered_strings)

Original List of Strings: ['hello', 'world', 'python', 'programming', 'ai']
Filtered Strings with More than Three Vowels: []


- def count_vowels(string): This line defines a function named count_vowels that counts the number of vowels in a string.
- (1 for char in string.lower() if char in 'aeiou') Calculates the count of vowels in the string, irrespective of case.
- string_list = ["hello", "world", "python", "programming", "ai"] Initializes a sample list of strings.
- [string for string in string_list if count_vowels(string) > 3] Uses list comprehension to filter strings with more than three vowels:
- for string in string_list iterates through each string in the list if count_vowels(string) > 3 checks if the count of vowels in the string is greater than 3.
- print("Original List of Strings:", string_list) Prints the original list of strings.
- print("Filtered Strings with More than Three Vowels:", filtered_strings) Prints the list containing strings with more than three vowels.

### 39. Develop a program that calculates the sum of the digits of numbers from 1 to 1000 using list comprehension.

In [7]:
# Using list comprehension to calculate the sum of digits for numbers from 1 to 1000
sums_of_digits = [sum(int(digit) for digit in str(num)) for num in range(1, 1001)]

# Print the result
print("Sum of Digits for Numbers from 1 to 1000:", sums_of_digits)

Sum of Digits for Numbers from 1 to 1000: [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 

- [sum(int(digit) for digit in str(num)) for num in range(1, 1001)] Uses list comprehension to calculate the sum of digits for numbers from 1 to 1000:
- for num in range(1, 1001) iterates through numbers from 1 to 1000.
- str(num) converts each number to a string.
- int(digit) converts each digit in the string back to an integer.
- sum(...) calculates the sum of digits for each number.
- print("Sum of Digits for Numbers from 1 to 1000:", sums_of_digits) Prints the list containing the sum of digits for each number.

### 40. Write a program that generates a list of prime palindromic numbers using list comprehension.

In [8]:
# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Function to check if a number is palindromic
def is_palindromic(num):
    return str(num) == str(num)[::-1]

# Using list comprehension to generate a list of prime palindromic numbers
prime_palindromes = [num for num in range(1, 1000) if is_prime(num) and is_palindromic(num)]

# Print the result
print("Prime Palindromic Numbers:", prime_palindromes)

Prime Palindromic Numbers: [2, 3, 5, 7, 11, 101, 131, 151, 181, 191, 313, 353, 373, 383, 727, 757, 787, 797, 919, 929]


- def is_prime(num): This line defines a function named is_prime that checks if a number is prime.
- def is_palindromic(num): This line defines a function named is_palindromic that checks if a number is palindromic.
- [num for num in range(1, 1000) if is_prime(num) and is_palindromic(num)] Uses list comprehension to generate a list of prime palindromic numbers:
- for num in range(1, 1000) iterates through numbers from 1 to 999.
- if is_prime(num) and is_palindromic(num) checks if the number is both prime and palindromic.
- print("Prime Palindromic Numbers:", prime_palindromes) Prints the list containing prime palindromic numbers.